# Generated by Django 2.2.7 on 2019-12-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('unknown', 'unknown')], default='unknown', help_text='Age', max_length=16),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='approaches',
            field=models.BooleanField(default=False, help_text='Approaches'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='chasing',
            field=models.BooleanField(default=False, help_text='Chasing'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='climbing',
            field=models.BooleanField(default=False, help_text='Climbing'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('unknown', 'unknown')], default='unknown', help_text='Primary Fur Color', max_length=50),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='date',
            field=models.DateField(default='2000-01-01', help_text='Date'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='eating',
            field=models.BooleanField(default=False, help_text='Eating'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='foraging',
            field=models.BooleanField(default=False, help_text='Foraging'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='indifferent',
            field=models.BooleanField(default=False, help_text='Indifferent'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='kuks',
            field=models.BooleanField(default=False, help_text='Kuks'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), ('unknown', 'unknown')], default='unknown', help_text='Location', max_length=50),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='moans',
            field=models.BooleanField(default=False, help_text='Moans'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(default='None', help_text='Other Activities', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='quaas',
            field=models.BooleanField(default=False, help_text='Quaas'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='running',
            field=models.BooleanField(default=False, help_text='Running'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='runs_from',
            field=models.BooleanField(default=False, help_text='Runs From'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift', max_length=2),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(default='None', help_text='Specific Location', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_flags',
            field=models.BooleanField(default=False, help_text='Tail Flags'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.BooleanField(default=False, help_text='Tail Twitches'),
        ),
    ]
